# Generated by Django 4.1.7 on 2023-03-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeebackModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("email", models.EmailField(max_length=64)),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField(max_length=500)),
            ],
        ),
    ]
