# Generated by Django 4.1.7 on 2023-03-16 05:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feebackmodel",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feebackmodel",
            name="is_replied",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="feebackmodel",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
